In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df = pd.read_csv("/content/Iris.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.drop(columns='Id',inplace=True)

In [ ]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [48]:
grp = df.groupby('Species')

In [50]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [51]:
iris_setosa = grp.get_group("Iris-setosa")

In [52]:
iris_setosa.head(10)

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa
5            5.4           3.9            1.7           0.4  Iris-setosa
6            4.6           3.4            1.4           0.3  Iris-setosa
7            5.0           3.4            1.5           0.2  Iris-setosa
8            4.4           2.9            1.4           0.2  Iris-setosa
9            4.9           3.1            1.5           0.1  Iris-setosa

In [53]:
iris_setosa

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0             5.1           3.5            1.4           0.2  Iris-setosa
1             4.9           3.0            1.4           0.2  Iris-setosa
2             4.7           3.2            1.3           0.2  Iris-setosa
3             4.6           3.1            1.5           0.2  Iris-setosa
4             5.0           3.6            1.4           0.2  Iris-setosa
5             5.4           3.9            1.7           0.4  Iris-setosa
6             4.6           3.4            1.4           0.3  Iris-setosa
7             5.0           3.4            1.5           0.2  Iris-setosa
8             4.4           2.9            1.4           0.2  Iris-setosa
9             4.9           3.1            1.5           0.1  Iris-setosa
10            5.4           3.7            1.5           0.2  Iris-setosa
11            4.8           3.4            1.6           0.2  Iris-setosa
12            4.8           3.0            1.4           0.1  Iris-setosa
13            4.3           3.0            1.1           0.1  Iris-setosa
14            5.8           4.0            1.2           0.2  Iris-setosa
15            5.7           4.4            1.5           0.4  Iris-setosa
16            5.4           3.9            1.3           0.4  Iris-setosa
17            5.1           3.5            1.4           0.3  Iris-setosa
18            5.7           3.8            1.7           0.3  Iris-setosa
19            5.1           3.8            1.5           0.3  Iris-setosa
20            5.4           3.4            1.7           0.2  Iris-setosa
21            5.1           3.7            1.5           0.4  Iris-setosa
22            4.6           3.6            1.0           0.2  Iris-setosa
23            5.1           3.3            1.7           0.5  Iris-setosa
24            4.8           3.4            1.9           0.2  Iris-setosa
25            5.0           3.0            1.6           0.2  Iris-setosa
26            5.0           3.4            1.6           0.4  Iris-setosa
27            5.2           3.5            1.5           0.2  Iris-setosa
28            5.2           3.4            1.4           0.2  Iris-setosa
29            4.7           3.2            1.6           0.2  Iris-setosa
30            4.8           3.1            1.6           0.2  Iris-setosa
31            5.4           3.4            1.5           0.4  Iris-setosa
32            5.2           4.1            1.5           0.1  Iris-setosa
33            5.5           4.2            1.4           0.2  Iris-setosa
34            4.9           3.1            1.5           0.1  Iris-setosa
35            5.0           3.2            1.2           0.2  Iris-setosa
36            5.5           3.5            1.3           0.2  Iris-setosa
37            4.9           3.1            1.5           0.1  Iris-setosa
38            4.4           3.0            1.3           0.2  Iris-setosa
39            5.1           3.4            1.5           0.2  Iris-setosa
40            5.0           3.5            1.3           0.3  Iris-setosa
41            4.5           2.3            1.3           0.3  Iris-setosa
42            4.4           3.2            1.3           0.2  Iris-setosa
43            5.0           3.5            1.6           0.6  Iris-setosa
44            5.1           3.8            1.9           0.4  Iris-setosa
45            4.8           3.0            1.4           0.3  Iris-setosa
46            5.1           3.8            1.6           0.2  Iris-setosa
47            4.6           3.2            1.4           0.2  Iris-setosa
48            5.3           3.7            1.5           0.2  Iris-setosa
49            5.0           3.3            1.4           0.2  Iris-setosa

In [54]:
iris_setosa.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  50 non-null     float64
 1   SepalWidthCm   50 non-null     float64
 2   PetalLengthCm  50 non-null     float64
 3   PetalWidthCm   50 non-null     float64
 4   Species        50 non-null     object
dtypes: float64(4), object(1)
memory usage: 2.3+ KB

In [55]:
iris_setosa.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count       50.00000     50.000000      50.000000      50.00000
mean         5.00600      3.418000       1.464000       0.24400
std          0.35249      0.381024       0.173511       0.10721
min          4.30000      2.300000       1.000000       0.10000
25%          4.80000      3.125000       1.400000       0.20000
50%          5.00000      3.400000       1.500000       0.20000
75%          5.20000      3.675000       1.575000       0.30000
max          5.80000      4.400000       1.900000       0.60000

In [56]:
iris_versicolor = grp.get_group('Iris-versicolor')

In [57]:
iris_versicolor

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
50            7.0           3.2            4.7           1.4  Iris-versicolor
51            6.4           3.2            4.5           1.5  Iris-versicolor
52            6.9           3.1            4.9           1.5  Iris-versicolor
53            5.5           2.3            4.0           1.3  Iris-versicolor
54            6.5           2.8            4.6           1.5  Iris-versicolor
55            5.7           2.8            4.5           1.3  Iris-versicolor
56            6.3           3.3            4.7           1.6  Iris-versicolor
57            4.9           2.4            3.3           1.0  Iris-versicolor
58            6.6           2.9            4.6           1.3  Iris-versicolor
59            5.2           2.7            3.9           1.4  Iris-versicolor
60            5.0           2.0            3.5           1.0  Iris-versicolor
61            5.9           3.0            4.2           1.5  Iris-versicolor
62            6.0           2.2            4.0           1.0  Iris-versicolor
63            6.1           2.9            4.7           1.4  Iris-versicolor
64            5.6           2.9            3.6           1.3  Iris-versicolor
65            6.7           3.1            4.4           1.4  Iris-versicolor
66            5.6           3.0            4.5           1.5  Iris-versicolor
67            5.8           2.7            4.1           1.0  Iris-versicolor
68            6.2           2.2            4.5           1.5  Iris-versicolor
69            5.6           2.5            3.9           1.1  Iris-versicolor
70            5.9           3.2            4.8           1.8  Iris-versicolor
71            6.1           2.8            4.0           1.3  Iris-versicolor
72            6.3           2.5            4.9           1.5  Iris-versicolor
73            6.1           2.8            4.7           1.2  Iris-versicolor
74            6.4           2.9            4.3           1.3  Iris-versicolor
75            6.6           3.0            4.4           1.4  Iris-versicolor
76            6.8           2.8            4.8           1.4  Iris-versicolor
77            6.7           3.0            5.0           1.7  Iris-versicolor
78            6.0           2.9            4.5           1.5  Iris-versicolor
79            5.7           2.6            3.5           1.0  Iris-versicolor
80            5.5           2.4            3.8           1.1  Iris-versicolor
81            5.5           2.4            3.7           1.0  Iris-versicolor
82            5.8           2.7            3.9           1.2  Iris-versicolor
83            6.0           2.7            5.1           1.6  Iris-versicolor
84            5.4           3.0            4.5           1.5  Iris-versicolor
85            6.0           3.4            4.5           1.6  Iris-versicolor
86            6.7           3.1            4.7           1.5  Iris-versicolor
87            6.3           2.3            4.4           1.3  Iris-versicolor
88            5.6           3.0            4.1           1.3  Iris-versicolor
89            5.5           2.5            4.0           1.3  Iris-versicolor
90            5.5           2.6            4.4           1.2  Iris-versicolor
91            6.1           3.0            4.6           1.4  Iris-versicolor
92            5.8           2.6            4.0           1.2  Iris-versicolor
93            5.0           2.3            3.3           1.0  Iris-versicolor
94            5.6           2.7            4.2           1.3  Iris-versicolor
95            5.7           3.0            4.2           1.2  Iris-versicolor
96            5.7           2.9            4.2           1.3  Iris-versicolor
97            6.2           2.9            4.3           1.3  Iris-versicolor
98            5.1           2.5            3.0           1.1  Iris-versicolor
99            5.7           2.8            4.1           1.3  Iris-versicolor

In [58]:
iris_versicolor.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count      50.000000     50.000000      50.000000     50.000000
mean        5.936000      2.770000       4.260000      1.326000
std         0.516171      0.313798       0.469911      0.197753
min         4.900000      2.000000       3.000000      1.000000
25%         5.600000      2.525000       4.000000      1.200000
50%         5.900000      2.800000       4.350000      1.300000
75%         6.300000      3.000000       4.600000      1.500000
max         7.000000      3.400000       5.100000      1.800000

In [59]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [61]:
iris_virginica = grp.get_group("Iris-virginica")

In [62]:
iris_virginica.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count       50.00000     50.000000      50.000000      50.00000
mean         6.58800      2.974000       5.552000       2.02600
std          0.63588      0.322497       0.551895       0.27465
min          4.90000      2.200000       4.500000       1.40000
25%          6.22500      2.800000       5.100000       1.80000
50%          6.50000      3.000000       5.550000       2.00000
75%          6.90000      3.175000       5.875000       2.30000
max          7.90000      3.800000       6.900000       2.50000

In [64]:
iris_virginica.mean()

<ipython-input-64-4321a7fe8aa7>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  iris_virginica.mean()

SepalLengthCm    6.588
SepalWidthCm     2.974
PetalLengthCm    5.552
PetalWidthCm     2.026
dtype: float64

In [75]:
print(iris_virginica.describe())

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count       50.00000     50.000000      50.000000      50.00000
mean         6.58800      2.974000       5.552000       2.02600
std          0.63588      0.322497       0.551895       0.27465
min          4.90000      2.200000       4.500000       1.40000
25%          6.22500      2.800000       5.100000       1.80000
50%          6.50000      3.000000       5.550000       2.00000
75%          6.90000      3.175000       5.875000       2.30000
max          7.90000      3.800000       6.900000       2.50000

In [76]:
print(" 1. Iris_virginica\n 2. Iris-versicolor \n 3. Iris-setosa \n 4. exit")
choice = ''
while(choice!='exit'):
  choice = input("Enter your choice: ")
  
  if(choice == 'Iris_virginica'):
    print("Iris_virginica")
    print(iris_virginica.describe())
  elif(choice=='Iris-versicolor'):
    print("Iris-versicolor")
    print(iris_versicolor.describe())
  elif(choice=='Iris-setosa'):
    print("Iris-setosa")
    print(iris_setosa.descirbe())
  else:
    print("Thank You")

1. iris_virginica
 2. Iris-versicolor
 3. Iris-setosa
 4. exit
Enter your choice: iris_virginica
       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count       50.00000     50.000000      50.000000      50.00000
mean         6.58800      2.974000       5.552000       2.02600
std          0.63588      0.322497       0.551895       0.27465
min          4.90000      2.200000       4.500000       1.40000
25%          6.22500      2.800000       5.100000       1.80000
50%          6.50000      3.000000       5.550000       2.00000
75%          6.90000      3.175000       5.875000       2.30000
max          7.90000      3.800000       6.900000       2.50000
Enter your choice: exit
Thank You